apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      name: cql
    - port: 7000
      name: clusterport
  selector:
    app: cassandra

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: cassandra
          image: bitnami/cassandra:3.11.4
          env:
            - name: CASSANDRA_USER
              value: cassandra
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CASSANDRA_PASSWORD
            - name: CASSANDRA_PASSWORD_SEEDER
              value: 'yes'
            - name: CASSANDRA_HOST
              value: "cassandra-0.cassandra.master.svc.cluster.local"
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: cassandra-data
              mountPath: /bitnami
            - name: config-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-volume
          configMap:
            name: cassandra-configs
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
