apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      name: clientport
    - port: 7000
      name: clusterport
  selector:
    app: cassandra

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: cassandra
          image: bitnami/cassandra:3.11.4
          env:
            - name: CASSANDRA_USER
              value: cassandra
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CASSANDRA_PASSWORD
          ports:
            - containerPort: 9042
              name: clientport
            - containerPort: 7000
              name: clusterport
          volumeMounts:
            - name: cassandra-data
              mountPath: /bitnami
            - name: config-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-volume
          configMap:
            name: cassandra-configs
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
