apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    ingressClassName: "traefik"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: timepicker-tls
      hosts:
        - timepicker.kuzznya.com
  rules:
    - host: timepicker.kuzznya.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

---

# copy of frontend-ingress with 'web' entrypoint and 'default-redirect' middleware to redirect http to https
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-redirect
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  tls:
    - secretName: main-tls
      hosts:
        - timepicker.kuzznya.com
  rules:
    - host: timepicker.kuzznya.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
      name: http80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/kuzznya/timepicker/frontend:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: ENV_API_PATH
              value: "https://timepicker.kuzznya.com"
            - name: ENV_AUTH_PATH
              value: "https://auth.kuzznya.com"
          ports:
            - containerPort: 8080
