apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http8080
  selector:
    app: keycloak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:15.0.2
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYCLOAK_PASSWORD
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: postgres
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: KEYCLOAK_DB_PASSWORD
          ports:
            - containerPort: 8080
              name: http8080

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: pgport
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: keycloak-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: registry.gitlab.com/alpeconsulting/sap-access/postgres-db:master
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: KEYCLOAK_DB_PASSWORD
          ports:
            - containerPort: 5432
              name: pgport
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: keycloak-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
