apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-service-ingress
  annotations:
    ingressClassName: "traefik"
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: timepicker.kuzznya.space
      http:
        paths:
          - path: /api/votes
            pathType: Prefix
            backend:
              service:
                name: vote-service
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http80
    - port: 8080
      targetPort: 8080
      name: http8080
  selector:
    app: vote-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
  labels:
    app: vote-service
spec:
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: ghcr.io/kuzznya/timepicker/vote-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CASSANDRA_URL
              value: cassandra:9042
            - name: CASSANDRA_USERNAME
              value: cassandra
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CASSANDRA_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KEYCLOAK_URL
              value: http://keycloak:8080/auth/realms/timepicker
