apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: websocket-service-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix('/ws') # && Host(``)
      kind: Rule
      services:
        - name: websocket-service
          port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-service-ingress
  annotations:
    ingressClassName: "traefik"
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: websocket-service
                port:
                  number: 80
          - path: /sessions
            pathType: Prefix
            backend:
              service:
                name: websocket-service
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http80
    - port: 8080
      targetPort: 8080
      name: http8080
  selector:
    app: websocket-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  labels:
    app: websocket-service
spec:
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: ghcr.io/kuzznya/timepicker/websocket-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KEYCLOAK_URL
              value: http://keycloak:8080/auth/realms/timepicker
