version: '3.8'

services:
#  db:
#    image: postgres:13
#    container_name: db
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    restart: unless-stopped

  cassandra:
    image: bitnami/cassandra:3.11.4
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra-data:/bitnami
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra


  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - 2181
    volumes:
      - zookeeper-data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    restart: unless-stopped

  kafka:
    depends_on:
      - zookeeper
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/bitnami
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:0.3.3
    container_name: kafka-ui
    ports:
      - 8888:8888
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      SERVER_PORT: 8888

  keycloak:
    depends_on:
      - keycloak-db
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USER: admin
      DB_PASSWORD: password
    ports:
      - "8000:8080"
    restart: unless-stopped

  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    volumes:
      - kc-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
  cassandra-data:
  zookeeper-data:
  kafka-data:
  kc-db-data:
