quarkus:
  application:
    name: websocket-service
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: '*'
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: '*'
    auth:
      permission:
        ws:
          paths: '/api/ws/*'
          policy: permit
        health:
          paths: '/q/health/*'
          policy: permit
        authenticated:
          paths: '/api/ws/sessions'
          policy: authenticated
          auth-mechanism: bearer
  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8000/realms/timepicker}
    application-type: service
    client-id: timepicker-backend
    credentials:
      secret: ${KEYCLOAK_SECRET}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: false
    devservices:
      enabled: false
  redis:
    hosts: ${REDIS_URL:redis://localhost:6379}
    devservices:
      enabled: false
  kafka:
    devservices:
      enabled: false
  container-image:
    image: ghcr.io/kuzznya/timepicker/websocket-service:latest
    username: ${DOCKER_USERNAME:}
    password: ${DOCKER_PASSWORD:}

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp:
  messaging:
    outgoing:
      votes:
        topic: votes
    incoming:
      user-votes:
        topic: user-votes
        group:
          id: websocket-service
        client:
          id: ${quarkus.uuid}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
      statistics:
        topic: statistics
        group:
          id: websocket-service
        client:
          id: ${quarkus.uuid}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer

"%dev":
  quarkus:
    http:
      port: 4100
    log:
      console:
        json: false
