quarkus:
  application:
    name: event-service
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: '*'
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: '*'
    auth:
      permission:
        health:
          paths: '/q/health/*'
          policy: permit
        authenticated:
          paths: '/*'
          policy: authenticated
          auth-mechanism: bearer
  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8000/auth/realms/timepicker}
    application-type: service
    client-id: timepicker-backend
    credentials:
      secret: ${KEYCLOAK_SECRET}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: false
    devservices:
      enabled: false
  kafka:
    devservices:
      enabled: false
  cassandra:
    contact-points: ${CASSANDRA_URL:localhost:9042}
    local-datacenter: datacenter1
    keyspace: events
    auth:
      username: ${CASSANDRA_USERNAME:cassandra}
      password: ${CASSANDRA_PASSWORD:cassandra}
    init:
      eager-init: true
  container-image:
    image: ghcr.io/kuzznya/timepicker/event-service:latest
    username: ${DOCKER_USERNAME:}
    password: ${DOCKER_PASSWORD:}

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp:
  messaging:
    outgoing:
      events:
        connector: smallrye-kafka
        topic: events

"%dev":
  quarkus:
    http:
      port: 4200
    log:
      console:
        json: false
