name: 'event-service CI/CD'

on:
  push:
    branches:
      - master
    paths:
      - event-service/**
      - .github/workflows/event-service.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build and push the image
        run: ./gradlew :event-service:build -Dquarkus.container-image.push=true
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
