name: 'frontend CI/CD'

on:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t ghcr.io/kuzznya/timepicker/frontend:latest .
        working-directory: frontend
      - name: Login with docker
        run: >
          echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.actor }}
          --password-stdin ghcr.io
      - name: Publish container
        run: docker push ghcr.io/kuzznya/timepicker/frontend --all-tags
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .kube directory
        run: mkdir ~/.kube || echo "Cannot create ~/.kube directory, skipping"
      - name: Prepare kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment frontend --namespace timepicker
