name: 'websocket-service CI/CD'

on:
  push:
    branches:
      - master
    paths:
      - websocket-service/**
      - .github/workflows/websocket-service.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build and push the image
        run: ./gradlew :websocket-service:build -Dquarkus.container-image.push=true
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .kube directory
        run: mkdir ~/.kube || echo "Cannot create ~/.kube directory, skipping"
      - name: Prepare kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment websocket-service --namespace timepicker
