quarkus:
  application:
    name: vote-service
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: '*'
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: '*'
    auth:
      permission:
        health:
          paths: '/q/health/*'
          policy: permit
        authenticated:
          paths: '/*'
          policy: authenticated
          auth-mechanism: bearer
  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8000/auth/realms/timepicker}
    application-type: service
    client-id: timepicker-backend
    credentials:
      secret: ${KEYCLOAK_SECRET}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: false
    devservices:
      enabled: false
  kafka:
    devservices:
      enabled: false
  cassandra:
    contact-points: ${CASSANDRA_URL:localhost:9042}
    local-datacenter: datacenter1
    keyspace: votes
    auth:
      username: ${CASSANDRA_USERNAME:cassandra}
      password: ${CASSANDRA_PASSWORD:cassandra}
    init:
      eager-init: true
  container-image:
    image: ghcr.io/kuzznya/timepicker/vote-service:latest
    username: ${DOCKER_USERNAME:}
    password: ${DOCKER_PASSWORD:}


kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp:
  messaging:
    incoming:
      votes:
        connector: smallrye-kafka
        topic: votes
        group:
          id: vote-service
        client:
          id: ${quarkus.uuid}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
      events:
        connector: smallrye-kafka
        topic: events
        group:
          id: vote-service
        client:
          id: ${quarkus.uuid}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
    outgoing:
      user-votes:
        connector: smallrye-kafka
        topic: user-votes
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      event-user-votes:
        connector: smallrye-kafka
        topic: user-votes
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      statistics:
        connector: smallrye-kafka
        topic: statistics

"%dev":
  quarkus:
    http:
      port: 4300
    log:
      console:
        json: false
